BlogApp/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogApp.Models;
using BlogApp.Filters;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace BlogApp.Controllers
{
    
    public class BlogController : Controller
    {
        private readonly BlogContext _context;
        private readonly IWebHostEnvironment _host;

        public BlogController(BlogContext context, IWebHostEnvironment host)
        {
            _context = context;
            this._host = host;
        }

        [IsLogin]
        // GET: Blog
        public async Task<IActionResult> Index()
        {
            var blogContext = _context.Blogs.Include(b => b.Category);

            return View(await blogContext.OrderByDescending(blog => blog.EklenmeTarihi).ToListAsync());


        }

        public IActionResult List(int? id, string q)
        {
            var bloglar = _context.Blogs
                .Where(i => i.Onay == true && i.Anasayfa == true) 
                .Select(i => new BlogModel()
                {
                    Id = i.Id,
                    Baslik = i.Baslik,
                    Aciklama = i.Aciklama,
                    EklenmeTarihi = i.EklenmeTarihi,
                    Onay = i.Onay,
                    Anasayfa = i.Anasayfa,
                    Resim = i.Resim,
                    CategoryId = i.CategoryId


                }).AsQueryable();
            if (string.IsNullOrEmpty(q)==false)
            {
                bloglar = bloglar.Where(i => i.Baslik.Contains(q) || i.Aciklama.Contains(q));
            }
            if (id != null)
            {
                bloglar = bloglar.Where(i => i.CategoryId == id);
            }
            return View(bloglar.OrderByDescending(bloglar => bloglar.EklenmeTarihi).ToList());
                

        }

        
        // GET: Blog/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .Include(b => b.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        [IsLogin]
        // GET: Blog/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "KategoriAdi");
            return View();
        }

        // POST: Blog/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [IsLogin]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Baslik,Aciklama,ImageFile,Icerik,Onay,Anasayfa,CategoryId")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                // save image to wwwroot/image
                string wwwRootPath = _host.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(blog.ImageFile.FileName);
                string extension = Path.GetExtension(blog.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/Image/", fileName);

                using (var fileStream = new FileStream(path,FileMode.Create))
                {
                    await blog.ImageFile.CopyToAsync(fileStream);
                }
                

                blog.Resim = fileName;
                blog.EklenmeTarihi = DateTime.Now;
                _context.Add(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "KategoriAdi", blog.CategoryId);
            return View(blog);
        }

        [IsLogin]
        [HttpPost]
        public IActionResult UploadCKEditor(IFormFile upload)
        {
            
            var filename = DateTime.Now.ToString("yyyyMMddHHmmss") + upload.FileName;
            var path = Path.Combine(_host.WebRootPath + "/uploads/", filename);
            var stream = new FileStream(path, FileMode.Create);
            upload.CopyToAsync(stream);
            return new JsonResult(new
            {
                uploaded = 1,
                fileName = upload.FileName,
                url = "/uploads/" + filename
            });
            
        }

        [IsLogin]
        // GET: Blog/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs.FindAsync(id);
            if (blog == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "KategoriAdi", blog.CategoryId);
            return View(blog);
        }

        // POST: Blog/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [IsLogin]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Baslik,Aciklama,Resim,ImageFile,Icerik,Onay,Anasayfa,CategoryId")] Blog blog)
        {
            if (id != blog.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var entity = _context.Blogs.Find(id);
                    if (entity != null)
                    {
                        entity.Baslik = blog.Baslik;
                        entity.Aciklama = blog.Aciklama;
                        entity.Icerik = blog.Icerik;
                        entity.Onay = blog.Onay;
                        entity.Anasayfa = blog.Anasayfa;
                        entity.CategoryId = blog.CategoryId;
                        
                    }
                    var imagepath = Path.Combine(_host.WebRootPath, "image", entity.Resim);
                    if (System.IO.File.Exists(imagepath))
                    {
                        System.IO.File.Delete(imagepath);
                    }

                    string wwwRootPath = _host.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(blog.ImageFile.FileName);
                    string extension = Path.GetExtension(blog.ImageFile.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    string path = Path.Combine(wwwRootPath + "/Image/", fileName);
                    
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await blog.ImageFile.CopyToAsync(fileStream);
                    }


                    entity.ImageFile = blog.ImageFile;
                    entity.Resim = fileName;

                    _context.Update(entity);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "KategoriAdi", blog.CategoryId);
            return View(blog);
        }
        [IsLogin]
        // GET: Blog/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .Include(b => b.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blog/Delete/5
        [IsLogin]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            
            var blog = await _context.Blogs.FindAsync(id);
            if (blog.Resim!=null)
            {
                var imagepath = Path.Combine(_host.WebRootPath, "image", blog.Resim);
                if (System.IO.File.Exists(imagepath))
                {
                    System.IO.File.Delete(imagepath);
                }
            }
            
            _context.Blogs.Remove(blog);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogExists(int id)
        {
            return _context.Blogs.Any(e => e.Id == id);
        }
    }
}

BlogApp/Controllers/NewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogApp.Models;
using BlogApp.Filters;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace BlogApp.Controllers
{
    
    public class NewController : Controller
    {
        private readonly BlogContext _context;
        private readonly IWebHostEnvironment _host;

        public NewController(BlogContext context, IWebHostEnvironment host)
        {
            _context = context;
            this._host = host;
        }
        [IsLogin]
        // GET: New
        public async Task<IActionResult> Index()
        {
            return View(await _context.News.OrderByDescending(r=>r.HaberEklenmeTarihi).ToListAsync());
        }

        // GET: New/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @new = await _context.News
                .FirstOrDefaultAsync(m => m.NewId == id);
            if (@new == null)
            {
                return NotFound();
            }

            return View(@new);
        }
        [IsLogin]
        // GET: New/Create
        public IActionResult Create()
        {
            return View();
        }
        [IsLogin]
        // POST: New/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NewId,HaberBaslik,HaberIcerik,ImageFile,Resim")] New @new)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _host.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(@new.ImageFile.FileName);
                string extension = Path.GetExtension(@new.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/Image/", fileName);

                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await @new.ImageFile.CopyToAsync(fileStream);
                }
                @new.Resim = fileName;
                @new.HaberEklenmeTarihi = DateTime.Now;
                _context.Add(@new);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@new);
        }
        [IsLogin]
        // GET: New/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @new = await _context.News.FindAsync(id);
            if (@new == null)
            {
                return NotFound();
            }
            return View(@new);
        }
        [IsLogin]
        // POST: New/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NewId,HaberBaslik,HaberIcerik,ImageFile,Resim")] New @new)
        {
            //if (id != @new.NewId)
            //{
            //    return NotFound();
            //}

            if (ModelState.IsValid)
            {
                try
                {
                    var entity = _context.News.Find(id);
                    if (entity!=null)
                    {
                        entity.HaberBaslik = @new.HaberBaslik;
                        entity.HaberIcerik = @new.HaberIcerik;
                        var imagepath = Path.Combine(_host.WebRootPath, "image", entity.Resim);
                        if (System.IO.File.Exists(imagepath))
                        {
                            System.IO.File.Delete(imagepath);
                        }
                        string wwwRootPath = _host.WebRootPath;
                        string fileName = Path.GetFileNameWithoutExtension(@new.ImageFile.FileName);
                        string extension = Path.GetExtension(@new.ImageFile.FileName);
                        fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        string path = Path.Combine(wwwRootPath + "/Image/", fileName);

                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await @new.ImageFile.CopyToAsync(fileStream);
                        }
                        entity.ImageFile = @new.ImageFile;
                        entity.Resim = fileName;


                    }
                    
                    _context.Update(entity);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewExists(@new.NewId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@new);
        }
        [IsLogin]
        // GET: New/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @new = await _context.News
                .FirstOrDefaultAsync(m => m.NewId == id);
            if (@new == null)
            {
                return NotFound();
            }

            return View(@new);
        }
        [IsLogin]
        // POST: New/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @new = await _context.News.FindAsync(id);
            
            if (@new.Resim != null)
            {
                var imagepath = Path.Combine(_host.WebRootPath, "image", @new.Resim);
                if (System.IO.File.Exists(imagepath))
                {
                    System.IO.File.Delete(imagepath);
                }
            }
            _context.News.Remove(@new);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NewExists(int id)
        {
            return _context.News.Any(e => e.NewId == id);
        }
    }
}

BlogApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogApp</title>
    <link href="~/owlcarousel/dist/assets/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/owlcarousel/dist/assets/owl.theme.default.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.5.0/font/bootstrap-icons.min.css" integrity="sha512-xnP2tOaCJnzp2d2IqKFcxuOiVCbuessxM6wuiolT9eeEJCyy0Vhcwa4zQvdrZNVqlqaxXhHqsSV1Ww7T2jSCUQ==" crossorigin="anonymous" />
    <script src="https://kit.fontawesome.com/c2d763bf5f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/SlickNav/dist/slicknav.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container">
                <span><i class="bi bi-currency-bitcoin me-3"></i></span>
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">BlogApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1" id="menu">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="https://www.binance.com/tr" target="_blank">Coin Satın al</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">İletişim</a>
                        </li>
                        @await Component.InvokeAsync("CategoryList")
                        <li class="nav-item">
                            <button class="btn btn-outline-warning" type="submit" id="navbarbutton"><i class="bi bi-search"></i></button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="row">
            <form asp-controller="Blog" asp-action="List" method="get" class="search-box d-flex justify-content-center align-items-center">
                <input name="q" class="form-control w-75" id="searchinput">
                <span>
                    <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
                </span>
            </form>
        </div>
    </div>

    <div class="container body">
        @RenderBody()
    </div>


    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/owlcarousel/dist/owl.carousel.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/SlickNav/dist/jquery.slicknav.js"></script>
    <script>
        $(function () {
            $('#menu').slicknav();
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BlogApp/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogApp</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.5.0/font/bootstrap-icons.min.css" integrity="sha512-xnP2tOaCJnzp2d2IqKFcxuOiVCbuessxM6wuiolT9eeEJCyy0Vhcwa4zQvdrZNVqlqaxXhHqsSV1Ww7T2jSCUQ==" crossorigin="anonymous" />
    <script src="https://kit.fontawesome.com/c2d763bf5f.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script type="text/javascript" src="~/ckeditor/ckeditor.js"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlogApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Blog Ekle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Kategori Ekle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="New" asp-action="Index">Haber Ekle</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container body">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BlogApp/Views/Shared/_Search.cshtml
@using (Html.BeginForm("List", "Blog", FormMethod.Get))
{
<div>
    <h4>Blog Arama</h4>
    <hr />

    <div class="input-group me-2" type="search" placeholder="Blog Search" aria-label="Search">
        @Html.TextBox("q", null, new { @class = "form-control" })
        <span>
            <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
        </span>
    </div>
    
</div>
}